Repository nhnacademy-be10-1lluwa/bookstore-product-service, pull requests merged in 2025-07, with the labels that each got.

#232 [BUG]: remove Aladin Api Test
  src/test/java/com/nhnacademy/illuwa/d_book/book/service/AladinBookApiServiceTest.java
Labels: 🐛 bug

#234 [REFACTOR] 이미지 업로드 방식 변경
  src/main/java/com/nhnacademy/illuwa/d_review/review/controller/ReviewController.java
  src/main/java/com/nhnacademy/illuwa/d_review/review/dto/ReviewRequest.java
  src/main/java/com/nhnacademy/illuwa/d_review/review/service/Impl/ReviewServiceImpl.java
  src/main/java/com/nhnacademy/illuwa/d_review/review/service/ReviewService.java
Labels: ♻️ refactor, 💫FEAT

#235 [FEAT] Category API 연동
  src/main/java/com/nhnacademy/illuwa/d_book/book/controller/AdminBookController.java
  src/main/java/com/nhnacademy/illuwa/d_book/book/controller/BookController.java
  src/main/java/com/nhnacademy/illuwa/d_book/book/dto/request/BookApiRegisterRequest.java
  src/main/java/com/nhnacademy/illuwa/d_book/book/mapper/BookMapper.java
  src/main/java/com/nhnacademy/illuwa/d_book/book/service/BookService.java
  src/main/java/com/nhnacademy/illuwa/d_book/category/controller/CategoryController.java
  src/main/java/com/nhnacademy/illuwa/d_book/category/dto/CategoryCreateRequest.java
  src/main/java/com/nhnacademy/illuwa/d_book/category/dto/CategoryResponse.java
  src/main/java/com/nhnacademy/illuwa/d_book/category/repository/category/CategoryRepository.java
  src/main/java/com/nhnacademy/illuwa/d_book/category/service/CategoryService.java
  src/test/java/com/nhnacademy/illuwa/d_book/category/service/CategoryServiceTest.java
Labels: 💫FEAT

#249 [REFACTOR] 프론트 연동 관련 수정
  src/main/java/com/nhnacademy/illuwa/common/exception/GlobalExceptionHandler.java
  src/main/java/com/nhnacademy/illuwa/d_review/review/controller/ReviewController.java
  src/main/java/com/nhnacademy/illuwa/d_review/review/dto/ReviewRequest.java
  src/main/java/com/nhnacademy/illuwa/d_review/review/entity/ReviewImage.java
  src/main/java/com/nhnacademy/illuwa/d_review/review/repository/ReviewRepository.java
  src/main/java/com/nhnacademy/illuwa/d_review/review/service/Impl/ReviewServiceImpl.java
  src/main/java/com/nhnacademy/illuwa/d_review/review/service/ReviewService.java
Labels: ♻️ refactor, 💫FEAT

#257 Feat/admin manage page pagenation
  src/main/java/com/nhnacademy/illuwa/d_book/book/controller/AdminBookController.java
  src/main/java/com/nhnacademy/illuwa/d_book/book/dto/response/BookDetailWithExtraInfoResponse.java
  src/main/java/com/nhnacademy/illuwa/d_book/book/service/BookService.java
Labels: 🐛 bug, ♻️ refactor, 💫FEAT

#261 [FEAT] Tag api 연동
  src/main/java/com/nhnacademy/illuwa/common/dto/PageResponse.java
  src/main/java/com/nhnacademy/illuwa/d_book/tag/controller/AdminTagController.java
  src/main/java/com/nhnacademy/illuwa/d_book/tag/controller/TagController.java
  src/main/java/com/nhnacademy/illuwa/d_book/tag/dto/TagResponse.java
  src/main/java/com/nhnacademy/illuwa/d_book/tag/entity/Tag.java
  src/main/java/com/nhnacademy/illuwa/d_book/tag/service/TagService.java
  src/test/java/com/nhnacademy/illuwa/d_book/tag/controller/AdminTagControllerTest.java
  src/test/java/com/nhnacademy/illuwa/d_book/tag/service/TagServiceTest.java
Labels: 💫FEAT, 🧹 cleanup

#264 [FEAT] 카테고리 API 서비스 계층 및 DTO/Mapper 추가
  src/main/java/com/nhnacademy/illuwa/d_book/category/controller/CategoryController.java
  src/main/java/com/nhnacademy/illuwa/d_book/category/dto/CategoryFlatResponse.java
  src/main/java/com/nhnacademy/illuwa/d_book/category/dto/CategoryResponse.java
  src/main/java/com/nhnacademy/illuwa/d_book/category/service/CategoryService.java
Labels: 🐛 bug, ♻️ refactor, 💫FEAT

#268 [REFACTOR] 외래키 제약조건 해결 - 카테고리 및 태그 삭제 로직 수정
  src/main/java/com/nhnacademy/illuwa/d_book/category/repository/bookcategory/BookCategoryRepository.java
  src/main/java/com/nhnacademy/illuwa/d_book/category/service/CategoryService.java
  src/main/java/com/nhnacademy/illuwa/d_book/tag/entity/Tag.java
  src/main/java/com/nhnacademy/illuwa/d_book/tag/repository/BookTagRepository.java
  src/main/java/com/nhnacademy/illuwa/d_book/tag/service/TagService.java
  src/test/java/com/nhnacademy/illuwa/d_book/tag/service/TagServiceTest.java
Labels: ♻️ refactor, 💫FEAT

#271 [FEAT] 카테고리별 도서 조회 API
  src/main/java/com/nhnacademy/illuwa/d_book/book/controller/BookController.java
  src/main/java/com/nhnacademy/illuwa/d_book/book/dto/response/BookOrderResponse.java
  src/main/java/com/nhnacademy/illuwa/d_book/book/repository/BookRepositoryCustom.java
  src/main/java/com/nhnacademy/illuwa/d_book/book/repository/BookRepositoryCustomImpl.java
  src/main/java/com/nhnacademy/illuwa/d_book/book/service/BookService.java
  src/main/java/com/nhnacademy/illuwa/d_book/category/repository/category/CategoryRepository.java
Labels: 💫FEAT

#279 [REFACTOR] 도서 등록일 순 정렬 추가
  src/main/java/com/nhnacademy/illuwa/d_book/book/controller/AdminBookController.java
Labels: ♻️ refactor, 💫FEAT

#281 [FEAT] 도서 수량 업데이트 api 추가
  src/main/java/com/nhnacademy/illuwa/cart/dto/BookCountUpdateRequest.java
  src/main/java/com/nhnacademy/illuwa/d_book/book/controller/AdminBookController.java
  src/main/java/com/nhnacademy/illuwa/d_book/book/service/BookService.java
Labels: 💫FEAT

#283 Refactor/book search refactoring
  src/main/java/com/nhnacademy/illuwa/d_book/book/controller/BookController.java
  src/main/java/com/nhnacademy/illuwa/d_book/book/repository/BookSearchRepository.java
  src/main/java/com/nhnacademy/illuwa/d_book/book/service/BookService.java
  src/main/java/com/nhnacademy/illuwa/search/controller/BookSearchController.java
  src/main/java/com/nhnacademy/illuwa/search/document/BookDocument.java
  src/main/java/com/nhnacademy/illuwa/search/repository/BookSearchRepository.java
  src/main/java/com/nhnacademy/illuwa/search/service/BookSearchService.java
  src/test/java/com/nhnacademy/illuwa/d_book/book/controller/BookControllerTest.java
  src/test/java/com/nhnacademy/illuwa/d_book/book/service/BookServiceTest.java
Labels: ♻️ refactor, 💫FEAT

#285 [REFACTOR] 도서 검색 api 연동 수정
  pom.xml
  src/main/java/com/nhnacademy/illuwa/search/document/BookDocument.java
  src/main/java/com/nhnacademy/illuwa/search/service/BookSearchService.java
  src/main/resources/elasticsearch/books-mapping.json
  src/main/resources/elasticsearch/nori-settings.json
Labels: ♻️ refactor

#297 feat: 존재하는 리뷰 확인 api 새롭게 추가
  src/main/java/com/nhnacademy/illuwa/d_review/review/controller/ReviewController.java
  src/main/java/com/nhnacademy/illuwa/d_review/review/service/Impl/ReviewServiceImpl.java
  src/main/java/com/nhnacademy/illuwa/d_review/review/service/ReviewService.java
Labels: ♻️ refactor

#301 [FEAT] Bookmark
  src/main/java/com/nhnacademy/illuwa/d_book/book/controller/BookmarkController.java
  src/main/java/com/nhnacademy/illuwa/d_book/book/dto/response/BookmarkResponse.java
  src/main/java/com/nhnacademy/illuwa/d_book/book/entity/Bookmark.java
  src/main/java/com/nhnacademy/illuwa/d_book/book/repository/BookmarkRepository.java
  src/main/java/com/nhnacademy/illuwa/d_book/book/service/BookmarkService.java
  src/main/java/com/nhnacademy/illuwa/d_book/book/service/Impl/BookmarkServiceImpl.java
Labels: 💫FEAT

#306 [REFACTOR] 컨트롤러 매핑 경로 수정
  src/main/java/com/nhnacademy/illuwa/d_review/comment/controller/CommentController.java
  src/main/java/com/nhnacademy/illuwa/d_review/review/controller/ReviewController.java
  src/main/java/com/nhnacademy/illuwa/d_review/review/dto/ReviewResponse.java
  src/main/java/com/nhnacademy/illuwa/d_review/review/service/Impl/ReviewServiceImpl.java
  src/main/java/com/nhnacademy/illuwa/d_review/review/service/ReviewService.java
  src/main/java/com/nhnacademy/illuwa/d_review/reviewlike/controller/ReviewLikeController.java
  src/main/java/com/nhnacademy/illuwa/d_review/reviewlike/service/Impl/ReviewLikeServiceImpl.java
  src/main/java/com/nhnacademy/illuwa/d_review/reviewlike/service/ReviewLikeService.java
  src/main/java/com/nhnacademy/illuwa/infra/storage/FileUploadController.java
Labels: 🐛 bug, ♻️ refactor

#318 [FEAT] 리뷰-책제목/유저 좋아요한 도서 querydsl 새로 추가
  src/main/java/com/nhnacademy/illuwa/d_book/book/controller/BookLikeController.java
  src/main/java/com/nhnacademy/illuwa/d_book/book/repository/BookLikeQuerydslRepository.java
  src/main/java/com/nhnacademy/illuwa/d_book/book/repository/BookLikeRepository.java
  src/main/java/com/nhnacademy/illuwa/d_book/book/repository/Impl/BookLikeQuerydslRepositoryImpl.java
  src/main/java/com/nhnacademy/illuwa/d_book/book/repository/Impl/BookRepositoryCustomImpl.java
  src/main/java/com/nhnacademy/illuwa/d_book/book/service/BookLikeService.java
  src/main/java/com/nhnacademy/illuwa/d_book/book/service/Impl/BookLikeServiceImpl.java
  src/main/java/com/nhnacademy/illuwa/d_review/review/controller/ReviewController.java
  src/main/java/com/nhnacademy/illuwa/d_review/review/repository/Impl/ReviewQuerydslRepositoryImpl.java
  src/main/java/com/nhnacademy/illuwa/d_review/review/repository/ReviewQuerydslRepository.java
  src/main/java/com/nhnacademy/illuwa/d_review/review/repository/ReviewRepository.java
  src/main/java/com/nhnacademy/illuwa/d_review/review/service/Impl/ReviewServiceImpl.java
  src/main/java/com/nhnacademy/illuwa/d_review/review/service/ReviewService.java
  src/main/java/com/nhnacademy/illuwa/d_review/reviewlike/repository/ReviewLikeQuerydslRepository.java
  src/main/resources/static/image-test.html
Labels: 💫FEAT

#329 refactor: #326 좋아요한 도서목록 조회 api
  src/main/java/com/nhnacademy/illuwa/d_book/book/controller/BookLikeController.java
  src/main/java/com/nhnacademy/illuwa/d_book/book/dto/response/SimpleBookResponse.java
  src/main/java/com/nhnacademy/illuwa/d_book/book/mapper/BookResponseMapper.java
  src/main/java/com/nhnacademy/illuwa/d_book/book/service/BookLikeService.java
  src/main/java/com/nhnacademy/illuwa/d_book/book/service/Impl/BookLikeServiceImpl.java
Labels: 🐛 bug, ♻️ refactor

#342 [FIX] 도서 삭제 api 변경
  src/main/java/com/nhnacademy/illuwa/d_book/book/controller/AdminBookController.java
  src/main/java/com/nhnacademy/illuwa/d_book/book/repository/BookRepositoryCustom.java
  src/main/java/com/nhnacademy/illuwa/d_book/book/service/BookService.java
  src/test/java/com/nhnacademy/illuwa/d_book/book/controller/AdminBookControllerTest.java
Labels: 🐛 bug

#345 [FEAT] 프론트 동기화용 - 테스트코드 1차업로드
  src/main/java/com/nhnacademy/illuwa/d_book/book/controller/BookLikeController.java
  src/main/java/com/nhnacademy/illuwa/d_review/review/controller/ReviewController.java
  src/main/java/com/nhnacademy/illuwa/d_review/review/repository/Impl/ReviewQuerydslRepositoryImpl.java
  src/main/java/com/nhnacademy/illuwa/d_review/reviewlike/controller/ReviewLikeController.java
  src/main/java/com/nhnacademy/illuwa/infra/storage/FileUploadController.java
  src/test/java/com/nhnacademy/illuwa/d_review/review/ReviewControllerTest.java
  src/test/java/com/nhnacademy/illuwa/d_review/review/ReviewDtoUnitTest.java
  src/test/java/com/nhnacademy/illuwa/d_review/review/ReviewEntityUnitTest.java
  src/test/java/com/nhnacademy/illuwa/d_review/review/ReviewImageEntityUnitTest.java
  src/test/java/com/nhnacademy/illuwa/d_review/review/ReviewQuerydslRepositoryTest.java
Labels: 💫FEAT

#346 [REFACTOR] RESTful API 형식 리팩토링
  src/main/java/com/nhnacademy/illuwa/d_book/book/controller/AdminBookController.java
  src/main/java/com/nhnacademy/illuwa/d_book/book/controller/BookController.java
  src/main/java/com/nhnacademy/illuwa/d_book/book/controller/ExternalBookController.java
  src/main/java/com/nhnacademy/illuwa/d_book/book/repository/BookRepositoryCustom.java
  src/main/java/com/nhnacademy/illuwa/d_book/book/repository/Impl/BookRepositoryCustomImpl.java
  src/main/java/com/nhnacademy/illuwa/d_book/book/service/BookService.java
  src/test/java/com/nhnacademy/illuwa/d_book/book/controller/AdminBookControllerTest.java
  src/test/java/com/nhnacademy/illuwa/d_book/book/controller/BookControllerTest.java
Labels: ♻️ refactor

#347 [REFACTOR] RESTful api 반영 경로 수정
  src/main/java/com/nhnacademy/illuwa/d_book/book/controller/AdminBookController.java
  src/test/java/com/nhnacademy/illuwa/d_book/book/controller/AdminBookControllerTest.java
Labels: ♻️ refactor

#349 [FIX] minio delete logic edited
  src/main/java/com/nhnacademy/illuwa/d_book/book/controller/BookController.java
  src/main/java/com/nhnacademy/illuwa/d_review/review/service/Impl/ReviewServiceImpl.java
  src/main/java/com/nhnacademy/illuwa/infra/storage/FileUploadController.java
  src/main/java/com/nhnacademy/illuwa/infra/storage/MinioStorageService.java
Labels: 🐛 bug

#352 refactor: client 코드 수정
  src/main/java/com/nhnacademy/illuwa/common/client/order/OrderServiceClient.java
Labels: ♻️ refactor

#362 [FEAT] swagger-annotation
  src/main/java/com/nhnacademy/illuwa/d_book/book/controller/BookLikeController.java
  src/main/java/com/nhnacademy/illuwa/d_review/review/controller/ReviewController.java
  src/main/java/com/nhnacademy/illuwa/d_review/reviewlike/controller/ReviewLikeController.java
Labels: 💫FEAT

#367 [BUG] 도서 목록 조회 시 발생하는 1+N 해결
  src/main/java/com/nhnacademy/illuwa/d_book/book/entity/Book.java
  src/main/java/com/nhnacademy/illuwa/d_book/book/repository/BookRepository.java
  src/main/java/com/nhnacademy/illuwa/d_book/book/service/BookService.java
  src/main/java/com/nhnacademy/illuwa/d_book/category/entity/BookCategory.java
  src/main/java/com/nhnacademy/illuwa/d_book/category/entity/Category.java
  src/main/java/com/nhnacademy/illuwa/d_book/tag/entity/BookTag.java
  src/main/java/com/nhnacademy/illuwa/d_book/tag/entity/Tag.java
  src/test/java/com/nhnacademy/illuwa/search/service/BookSearchServiceTest.java
Labels: 🐛 bug, ♻️ refactor

#375 [Bug] 카테고리 pagination 관련 에러
  pom.xml
  src/main/java/com/nhnacademy/illuwa/d_book/book/mapper/BookMapper.java
  src/main/java/com/nhnacademy/illuwa/d_book/book/service/BookService.java
  src/main/java/com/nhnacademy/illuwa/d_book/category/controller/CategoryController.java
  src/main/java/com/nhnacademy/illuwa/d_book/category/repository/category/CategoryRepository.java
  src/main/java/com/nhnacademy/illuwa/d_book/category/service/CategoryService.java
  src/test/java/com/nhnacademy/illuwa/d_book/category/service/CategoryServiceTest.java
Labels: 🐛 bug

#376 [FEAT] 테스트 코드 추가
  src/main/java/com/nhnacademy/illuwa/d_book/category/controller/CategoryController.java
  src/test/java/com/nhnacademy/illuwa/d_book/book/service/BookServiceTest.java
  src/test/java/com/nhnacademy/illuwa/d_book/category/service/CategoryServiceTest.java
Labels: ✅ test
